-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Teams Table (Public profile for Auth Users)
create table public.teams (
  id uuid references auth.users not null primary key,
  team_id text unique not null,
  name text not null,
  coins int default 0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for teams
alter table public.teams enable row level security;

-- Policies for teams
create policy "Public teams are viewable by everyone."
  on public.teams for select
  using ( true );

create policy "Users can update own team."
  on public.teams for update
  using ( auth.uid() = id );

create policy "Users can insert own team."
  on public.teams for insert
  with check ( auth.uid() = id );

-- Posts Table
create table public.posts (
  id uuid default uuid_generate_v4() primary key,
  team_id uuid references public.teams(id) not null,
  content text not null,
  image_url text,
  is_tts boolean default false,
  is_song boolean default false,
  reactions jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for posts
alter table public.posts enable row level security;

create policy "Public posts are viewable by everyone."
  on public.posts for select
  using ( true );

create policy "Authenticated users can insert posts."
  on public.posts for insert
  with check ( auth.uid() = team_id );

-- Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price int not null,
  stock int default 0 not null,
  image text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for products
alter table public.products enable row level security;

create policy "Public products are viewable by everyone."
  on public.products for select
  using ( true );

-- Auctions Table
create table public.auctions (
  id bigint generated by default as identity primary key,
  item_name text not null,
  start_price int not null,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  status text default 'pending' check (status in ('pending', 'active', 'completed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for auctions
alter table public.auctions enable row level security;

create policy "Public auctions are viewable by everyone."
  on public.auctions for select
  using ( true );

-- Bids Table
create table public.bids (
  id bigint generated by default as identity primary key,
  auction_id bigint references public.auctions(id) not null,
  team_id uuid references public.teams(id) not null,
  amount int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for bids
alter table public.bids enable row level security;

create policy "Public bids are viewable by everyone."
  on public.bids for select
  using ( true );

create policy "Authenticated users can insert bids."
  on public.bids for insert
  with check ( auth.role() = 'authenticated' );

-- Media Queue Table
create table public.media_queue (
  id bigint generated by default as identity primary key,
  type text check (type in ('tts', 'song')),
  content text not null,
  team_id uuid references public.teams(id) not null,
  status text default 'pending' check (status in ('pending', 'played')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for media_queue
alter table public.media_queue enable row level security;

create policy "Public media queue is viewable by everyone."
  on public.media_queue for select
  using ( true );

create policy "Authenticated users can insert media requests."
  on public.media_queue for insert
  with check ( auth.role() = 'authenticated' );

-- Transactions Table (Log)
create table public.transactions (
  id bigint generated by default as identity primary key,
  team_id uuid references public.teams(id) not null,
  amount int not null,
  type text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for transactions
alter table public.transactions enable row level security;

create policy "Teams can view own transactions."
  on public.transactions for select
  using ( auth.uid() = team_id );

-- RPC: Buy Product
create or replace function buy_product(p_id bigint, t_id uuid)
returns void as $$
declare
  v_price int;
  v_stock int;
  v_coins int;
begin
  -- Get product info
  select price, stock into v_price, v_stock from public.products where id = p_id;
  
  if not found then
    raise exception 'Product not found';
  end if;

  if v_stock <= 0 then
    raise exception 'Out of stock';
  end if;

  -- Get team coins
  select coins into v_coins from public.teams where id = t_id;

  if v_coins < v_price then
    raise exception 'Not enough coins';
  end if;

  -- Deduct coins
  update public.teams set coins = coins - v_price where id = t_id;

  -- Decrement stock
  update public.products set stock = stock - 1 where id = p_id;

  -- Log transaction
  insert into public.transactions (team_id, amount, type, description)
  values (t_id, -v_price, 'buy', 'Bought product ' || p_id);
end;
$$ language plpgsql security definer;

-- RPC: Place Bid
create or replace function place_bid(a_id bigint, t_id uuid, bid_amount int)
returns void as $$
declare
  v_current_bid int;
  v_coins int;
  v_status text;
begin
  -- Get auction info
  select status into v_status from public.auctions where id = a_id;
  
  if v_status != 'active' then
    raise exception 'Auction is not active';
  end if;

  -- Get current highest bid
  select coalesce(max(amount), 0) into v_current_bid from public.bids where auction_id = a_id;

  if bid_amount <= v_current_bid then
    raise exception 'Bid must be higher than current bid';
  end if;

  -- Get team coins
  select coins into v_coins from public.teams where id = t_id;

  if v_coins < bid_amount then
    raise exception 'Not enough coins';
  end if;

  -- Insert bid
  insert into public.bids (auction_id, team_id, amount)
  values (a_id, t_id, bid_amount);
end;
$$ language plpgsql security definer;

-- Enable Realtime for tables
alter publication supabase_realtime add table public.posts;
alter publication supabase_realtime add table public.bids;
alter publication supabase_realtime add table public.media_queue;
