-- Likes Table
create table public.likes (
  id bigint generated by default as identity primary key,
  post_id uuid references public.posts(id) on delete cascade not null,
  team_id uuid references public.teams(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(post_id, team_id)
);

-- Enable RLS for likes
alter table public.likes enable row level security;

create policy "Public likes are viewable by everyone."
  on public.likes for select
  using ( true );

create policy "Authenticated users can insert likes."
  on public.likes for insert
  with check ( auth.uid() = team_id );

create policy "Users can delete own likes."
  on public.likes for delete
  using ( auth.uid() = team_id );

-- Comments Table
create table public.comments (
  id bigint generated by default as identity primary key,
  post_id uuid references public.posts(id) on delete cascade not null,
  team_id uuid references public.teams(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for comments
alter table public.comments enable row level security;

create policy "Public comments are viewable by everyone."
  on public.comments for select
  using ( true );

create policy "Authenticated users can insert comments."
  on public.comments for insert
  with check ( auth.uid() = team_id );

create policy "Users can delete own comments."
  on public.comments for delete
  using ( auth.uid() = team_id );

-- Enable Realtime
alter publication supabase_realtime add table public.likes;
alter publication supabase_realtime add table public.comments;
